root: ./

structure:  
    readme: basics/what-is-filecoin/README.md
    summary: SUMMARY.md

redirects:  
    about-filecoin/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
    about-filecoin/filecoin-compared-to: basics/project-and-community/filecoin-compared-to.md
    about-filecoin/network-performance: networks/mainnet/network-performance.md
    about-filecoin/project: basics/project-and-community.md
    about-filecoin/related-projects: basics/project-and-community/related-projects.md
    about-filecoin/social-media: basics/project-and-community/social-media.md
    about-filecoin/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
    about-filecoin/why-filecoin: basics/project-and-community/filecoin-faqs.md
    about/basics/filecoin-compared-to: basics/project-and-community/filecoin-compared-to.md
    about/basics/filecoin-faq: basics/project-and-community/filecoin-faqs.md
    about/basics/how-filecoin-works: basics/what-is-filecoin.md
    about/basics/introduction: basics/what-is-filecoin.md
    about/basics/what-is-filecoin: basics/what-is-filecoin.md
    about/community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
    about/community/social-media: basics/project-and-community/social-media.md
    about/contribute/contribution-tutorial: basics/project-and-community/ways-to-contribute.md
    about/contribute/grammar-and-formatting: basics/project-and-community/ways-to-contribute.md
    about/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
    about/contribute/writing-guide: basics/project-and-community/ways-to-contribute.md
    about/project/related-projects: basics/project-and-community/related-projects.md
    about/project/the-filecoin-project: basics/project-and-community/the-filecoin-project.md
    archive: https://github.com/filecoin-project/filecoin-docs.md
    basics: basics/what-is-filecoin.md
    basics/interplanetary-consensus/overview: basics/interplanetary-consensus/README.md
    basics/the-blockchain/tipsets: basics/the-blockchain/blocks-and-tipsets.md
    basics/what-is-filecoin/overview: basics/what-is-filecoin/README.md
    build: smart-contracts/fundamentals.md
    build/developer-tools/wallets-signing-tools-api-clients: reference/general/tools.md
    build/examples: smart-contracts/fundamentals.md
    build/examples/network-inspector/lotus-and-go-ipfs-interactions: https://lotus.filecoin.io.md
    build/examples/network-inspector/overview: smart-contracts/fundamentals.md
    build/examples/web-applications/overview: smart-contracts/fundamentals.md
    build/fvm/basics/tools: reference/general/tools.md
    build/get-building/overview: smart-contracts/fundamentals.md
    build/hosted-lotus: nodes/full-nodes/node-providers.md
    build/lotus/api-tokens: https://lotus.filecoin.io.md
    build/signing-libraries: reference/general/tools.md
    community: basics/project-and-community.md
    community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
    community/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
    community/social-media: basics/project-and-community/social-media.md
    community/social-media/social-media: basics/project-and-community/social-media.md
    developers/infrastructure/block-explorers: networks/mainnet/rpcs.md
    developers/infrastructure/how-tos/run-a-local-network: nodes/full-nodes.md
    developers/infrastructure/how-tos/spin-up-a-lite-node: nodes/lite-nodes/spin-up-a-lite-node.md
    developers/infrastructure/libraries: reference/general/tools.md
    developers/infrastructure/network-performance: networks/mainnet/network-performance.md
    developers/introduction/apps-and-filecoin: basics/what-is-filecoin.md
    developers/introduction/filecoin-and-ipfs: basics/what-is-filecoin.md
    developers/introduction/overview: basics/what-is-filecoin.md
    developers/reference/built-in-actors/account-actor: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/datacap: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/miner: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/multisig: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/storage-market-actor: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/storage-power-actor: reference/built-in-actors/protocol-api.md
    developers/reference/built-in-actors/verified-registry-actor: reference/built-in-actors/protocol-api.md
    developers/reference/json-rpc/auth: reference/json-rpc.md
    developers/reference/json-rpc/beacon: reference/json-rpc.md
    developers/reference/json-rpc/chain: reference/json-rpc.md
    developers/reference/json-rpc/client: reference/json-rpc.md
    developers/reference/json-rpc/create: reference/json-rpc.md
    developers/reference/json-rpc/eth: reference/json-rpc.md
    developers/reference/json-rpc/gas: reference/json-rpc.md
    developers/reference/json-rpc/i: reference/json-rpc.md
    developers/reference/json-rpc/introduction: reference/json-rpc.md
    developers/reference/json-rpc/log: reference/json-rpc.md
    developers/reference/json-rpc/market: reference/json-rpc.md
    developers/reference/json-rpc/miner: reference/json-rpc.md
    developers/reference/json-rpc/mpool: reference/json-rpc.md
    developers/reference/json-rpc/msig: reference/json-rpc.md
    developers/reference/json-rpc/net: reference/json-rpc.md
    developers/reference/json-rpc/paych: reference/json-rpc.md
    developers/reference/json-rpc/state: reference/json-rpc.md
    developers/reference/json-rpc/sync: reference/json-rpc.md
    developers/reference/json-rpc/wallet: reference/json-rpc.md
    developers/reference/specification: reference/general/specifications.md
    developers/reference/tools: reference/general/tools.md
    developers/smart-contracts/about/blueprints: smart-contracts/fundamentals/the-fvm.md
    developers/smart-contracts/about/faqs: smart-contracts/fundamentals/faqs.md
    developers/smart-contracts/about/project: smart-contracts/fundamentals.md
    developers/smart-contracts/about/support: smart-contracts/fundamentals/support.md
    developers/smart-contracts/about/use-cases: smart-contracts/fundamentals/the-fvm.md
    developers/smart-contracts/concepts/accounts-and-assets: smart-contracts/filecoin-evm-runtime/address-types.md
    developers/smart-contracts/concepts/actors-and-contracts: smart-contracts/filecoin-evm-runtime/actor-types.md
    developers/smart-contracts/concepts/ethereum-compatibility: smart-contracts/filecoin-evm-runtime/difference-with-ethereum.md
    developers/smart-contracts/concepts/filecoin-evm: smart-contracts/fundamentals/filecoin-evm-runtime.md
    developers/smart-contracts/concepts/tipsets: basics/the-blockchain/blocks-and-tipsets.md
    developers/smart-contracts/filecoin-virtual-machine: smart-contracts/fundamentals/the-fvm.md
    developers/smart-contracts/hardhat: smart-contracts/developing-contracts/hardhat.md
    developers/smart-contracts/how-tos/add-to-metamask: basics/assets/metamask-setup.md
    developers/smart-contracts/how-tos/calculate-gas: smart-contracts/filecoin-evm-runtime/how-gas-works.md
    developers/smart-contracts/how-tos/deploy-a-contract: smart-contracts/developing-contracts/remix.md
    developers/smart-contracts/how-tos/future-proof: smart-contracts/developing-contracts/best-practices.md
    developers/smart-contracts/how-tos/get-test-tokens: smart-contracts/developing-contracts/get-test-tokens.md
    developers/smart-contracts/how-tos/use-a-faucet: smart-contracts/developing-contracts/get-test-tokens.md
    developers/smart-contracts/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
    developers/storage-helpers/ceramic: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/estuary: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/how-tos/retrieve-data: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/nft-storage: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/overview: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/starling: basics/how-storage-works/storage-onramps.md
    developers/storage-helpers/web3-storage: basics/how-storage-works/storage-onramps.md
    fvm: smart-contracts/fundamentals/the-fvm.md
    fvm/basics/faqs: smart-contracts/fundamentals/faqs.md
    fvm/basics/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
    fvm/basics/support: smart-contracts/fundamentals/support.md
    fvm/concepts/accounts-and-assets: smart-contracts/filecoin-evm-runtime/address-types.md
    fvm/concepts/actors-and-contracts: smart-contracts/filecoin-evm-runtime/actor-types.md
    fvm/concepts/tipsets: basics/the-blockchain/blocks-and-tipsets.md
    fvm/how-tos/add-to-metamask: basics/assets/metamask-setup.md
    fvm/how-tos/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
    fvm/how-tos/use-a-faucet: smart-contracts/developing-contracts/get-test-tokens.md
    fvm/reference/tools: reference/general/tools.md
    get-started: basics/what-is-filecoin.md
    get-started/explore-the-network: basics/what-is-filecoin.md
    get-started/go-filecoin-tutorial/getting-started: basics/what-is-filecoin.md
    get-started/go-filecoin-tutorial/home: basics/what-is-filecoin.md
    get-started/go-filecoin-tutorial/storing-on-filecoin: basics/what-is-filecoin.md
    get-started/lotus: https://lotus.filecoin.io.md
    get-started/lotus/chain: https://lotus.filecoin.io.md
    get-started/lotus/configuration-and-advanced-usage: https://lotus.filecoin.io.md
    get-started/lotus/installation: https://lotus.filecoin.io.md
    get-started/lotus/send-and-receive-fil: https://lotus.filecoin.io.md
    get-started/lotus/switch-networks: https://lotus.filecoin.io.md
    get-started/overview: basics/what-is-filecoin.md
    get-started/overview/get-started: basics/what-is-filecoin.md
    get-started/store-and-retrieve/setup: https://lotus.filecoin.io.md
    get-started/store-and-retrieve/store-data: https://lotus.filecoin.io.md
    glossary: reference/general/glossary.md
    intro/intro-to-filecoin/blockchain: basics/the-blockchain.md
    intro/intro-to-filecoin/crypto-economics: basics/the-blockchain.md
    intro/intro-to-filecoin/network: basics/the-blockchain.md
    intro/intro-to-filecoin/programming-on-filecoin: basics/the-blockchain.md
    intro/intro-to-filecoin/retrieval-market: basics/the-blockchain.md
    intro/intro-to-filecoin/storage-market: basics/the-blockchain.md
    intro/intro-to-filecoin/storage-model: basics/the-blockchain.md
    intro/intro-to-filecoin/what-is-filecoin: basics/the-blockchain.md
    mine: storage-providers/basics.md
    mine/connectivity: storage-providers/basics.md
    mine/lotus: storage-providers/basics.md
    mine/lotus/miner-addresses: storage-providers/basics.md
    mine/lotus/miner-configuration: storage-providers/basics.md
    mine/lotus/miner-lifecycle: storage-providers/basics.md
    mine/lotus/miner-setup: storage-providers/basics.md
    mine/lotus/seal-workers: storage-providers/basics.md
    mine/lotus/sector-pledging: storage-providers/basics.md
    mine/mining-architectures: storage-providers/basics.md
    mine/slashing: storage-providers/basics.md
    mine/spacerace: storage-providers/basics.md
    networks: networks/mainnet.md
    networks/calibration: networks/mainnet.md
    networks/calibration/add-to-metamask: networks/mainnet.md
    networks/calibration/details: networks/calibration.md
    networks/hyperspace/add-to-metamask: networks/mainnet.md
    networks/hyperspace/details: networks/mainnet.md
    networks/hyperspace/explorers: networks/mainnet.md
    networks/hyperspace/get-test-tokens: networks/mainnet.md
    networks/hyperspace/rpcs: networks/mainnet.md
    networks/local-testnet: networks/mainnet.md
    networks/local-testnet/set-up: networks/local-testnet.md
    networks/mainnet: networks/mainnet.md
    networks/mainnet/add-to-metamask: networks/mainnet.md
    networks/mainnet/details: networks/mainnet.md
    networks/network-performance: networks/mainnet.md
    networks/overview: networks/mainnet.md
    networks/overview/network-performance: networks/mainnet.md
    networks/spacenet/details: networks/spacenet.md
    nodes/implementations/overview: nodes/implementations/README.md
    nodes/node-providers: nodes/implementations.md
    nodes/node-providers/ankr: nodes/implementations.md
    nodes/node-providers/chainstack: nodes/implementations.md
    nodes/node-providers/glif: nodes/implementations.md
    project: basics/project-and-community.md
    project/related-projects: basics/project-and-community/related-projects.md
    reference: reference/general.md
    reference/built-in-actors: reference/built-in-actors.md
    reference/built-in-actors/overview: reference/built-in-actors/README.md
    reference/exchanges: reference/exchanges.md
    reference/general: reference/general.md
    reference/glossary: reference/general/glossary.md
    reference/json-rpc: reference/json-rpc.md
    reference/json-rpc/introduction: reference/json-rpc.md
    reference/lotus-api: reference/json-rpc.md
    reference/reference/glossary: reference/general/glossary.md
    reference/reference/overview: reference/general.md
    smart-contracts: smart-contracts/fundamentals.md
    smart-contracts/advanced/bridges: smart-contracts/advanced/cross-chain-bridges.md
    smart-contracts/advanced/wfil: smart-contracts/advanced/wrapped-fil.md
    smart-contracts/developing-contracts: smart-contracts/developing-contracts.md
    smart-contracts/developing-contracts/ethereum-libraries: smart-contracts/developing-contracts/solidity-libraries.md
    smart-contracts/developing-contracts/solidity-libraries: smart-contracts/developing-contracts/filecoin.sol.md
    smart-contracts/developing-contracts/verify-contracts: smart-contracts/developing-contracts/verify-a-contract.md
    smart-contracts/filecoin-evm-runtime: smart-contracts/fundamentals/filecoin-evm-runtime.md
    smart-contracts/fundamentals: smart-contracts/fundamentals.md
    smart-contracts/fundamentals/overview: smart-contracts/fundamentals/README.md
    smart-contracts/fundamentals/the-filecoin-virtual-machine: smart-contracts/fundamentals/the-fvm.md
    smart-contracts/wallets/fil-to-zero-x: smart-contracts/filecoin-evm-runtime/filforwarder.md
    smart-contracts/wallets/filforwader: smart-contracts/filecoin-evm-runtime/filforwarder.md
    smart-contracts/wallets/transfer-fil: basics/assets/transfer-fil.md
    storage-provider: storage-providers/basics.md
    storage-provider/architecture/lotus-automation: storage-providers/architecture/lotus-automation.md
    storage-provider/architecture/lotus-components: storage-providers/architecture/lotus-components.md
    storage-provider/architecture/network-indexer: storage-providers/architecture/network-indexer.md
    storage-provider/architecture/sealing-as-a-service: storage-providers/architecture/sealing-as-a-service.md
    storage-provider/architecture/sealing-pipeline: storage-providers/architecture/sealing-pipeline.md
    storage-provider/architecture/sealing-rate: storage-providers/architecture/sealing-rate.md
    storage-provider/architecture/storage-provider-automation: storage-providers/architecture/lotus-automation.md
    storage-provider/architectures: storage-providers/architecture.md
    storage-provider/basics/overview: storage-providers/basics/README.md
    storage-provider/basics/quick-start-guide: storage-providers/basics/quickstart-guide.md
    storage-provider/filecoin-deals/auxiliary-services: storage-providers/filecoin-deals/auxiliary-services.md
    storage-provider/filecoin-deals/charging-for-data: storage-providers/filecoin-deals/charging-for-data.md
    storage-provider/filecoin-deals/filecoin-programs: storage-providers/filecoin-deals/filecoin-programs.md
    storage-provider/filecoin-deals/return-on-investment: storage-providers/filecoin-deals/return-on-investment.md
    storage-provider/filecoin-deals/snap-deals: storage-providers/filecoin-deals/snap-deals.md
    storage-provider/filecoin-deals/storage-deals: storage-providers/filecoin-deals/storage-deals.md
    storage-provider/filecoin-deals/verified-deals: storage-providers/filecoin-deals/verified-deals.md
    storage-provider/filecoin-economics/block-rewards: storage-providers/filecoin-economics/block-rewards.md
    storage-provider/filecoin-economics/committed-capacity: storage-providers/filecoin-economics/committed-capacity.md
    storage-provider/filecoin-economics/fil-collateral: storage-providers/filecoin-economics/fil-collateral.md
    storage-provider/filecoin-economics/slashing: storage-providers/filecoin-economics/slashing.md
    storage-provider/filecoin-economics/storage-proving: storage-providers/filecoin-economics/storage-proving.md
    storage-provider/infrastructure/backup: storage-providers/infrastructure/backup-and-disaster-recovery.md
    storage-provider/infrastructure/network: storage-providers/infrastructure/network.md
    storage-provider/infrastructure/reference-architectures: storage-providers/infrastructure/reference-architectures.md
    storage-provider/infrastructure/storage: storage-providers/infrastructure/storage.md
    storage-provider/overview: storage-providers.md
    storage-provider/rewards/slashing: basics/what-is-filecoin.md
    storage-provider/skills/industry: storage-providers/skills/industry.md
    storage-provider/skills/linux: storage-providers/skills/linux.md
    storage-provider/skills/network: storage-providers/skills/network.md
    storage-provider/skills/sales: storage-providers/skills/sales.md
    storage-provider/skills/security: storage-providers/skills/security.md
    storage-provider/skills/storage: storage-providers/skills/storage.md
    storage-provider/slashing: storage-providers/filecoin-economics/slashing.md
    storage-provider/storage-provider-architectures: storage-providers/infrastructure/reference-architectures.md
    store: basics/what-is-filecoin.md
    store/filecoin-plus: basics/what-is-filecoin.md
    store/filecoin-plus/overview: basics/what-is-filecoin.md
    store/lotus: basics/what-is-filecoin.md
    store/lotus/store-data: basics/what-is-filecoin.md
    store/overview/start-storing: basics/what-is-filecoin.md
    store/slate: basics/what-is-filecoin.md
    store/tools: basics/what-is-filecoin.md
    store/tools/estuary: basics/what-is-filecoin.md
    store/tools/starling: basics/what-is-filecoin.md
